apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - karpenter-values.yaml
  - karpenter-nodepool.yaml
  - karpenter-ec2nodeclass.yaml
  - nvidia-device-plugin.yaml
  - efa-device-plugin.yaml
  - aws-lb-controller.yaml
